# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q2ybqTBWzmsZ3TlXcrSfMan0VyNgoIiq
"""

from tensorflow import keras
from keras.preprocessing import image
import numpy as np
from keras.utils import load_img,img_to_array
model = keras.models.load_model('/content/drive/MyDrive/model.h5')
img_height, img_width = 244, 244
img_path = '/content/drive/MyDrive/fruts/dataset/dataset/test/rottenoranges/Screen Shot 2018-06-12 at 11.18.34 PM.png'
img =load_img(img_path, target_size=(img_height, img_width))
x = img_to_array(img)
x = np.expand_dims(x, axis=0)
x = x / 255.0
preds = model.predict(x)
print(preds)
if preds[0][0] > 0.5:
    print("The fruit is  apple fresh.")
elif preds[0][1] > 0.5:
  print("The fruit is  banana fresh.")
elif preds[0][2] > 0.5:
  print("The fruit is  orange fresh.")
elif preds[0][3] > 0.5:
  print("The fruit is   rotten apple.")
elif preds[0][4] > 0.5:
  print("The fruit is  rotten banaba.")
else:
    print("The fruit is rotten oranges.")

from google.colab import drive
drive.mount('/content/drive')